### PR TITLE
No more need to "from django_replicated.settings import *"

### PR DESCRIPTION
**Pull request by alanjds**
The resulting code is ~~not nice but is yet still better~~ cleaner and nicer

### CODE REVIEW

**Comment by alanjds** [comment]
Realized that I had to change the tests to actually test stuff without "import *". With it, what worked still works, but without, some tests are broken.

I guess the tests are broken, not the code, but cannot assure it.

**Comment by alanjds** [comment]
Now it works, passes the tests and is way cleaner than before

**Comment by alanjds** [comment]
Now I think its ready to be merged. Sorry for too many updates.

**Comment by daevaorn** [comment]
Hi, Alan.

Thanks for your contribution.

The problem you are trying to solve isn't a problem at all. Import of application settings in `settings.py` is a common practice, and I don't thing we have to change it. It is explicit and does not require additional code to support settings overrides.

**Comment by alanjds** [comment]
Ok. So I suggest the settings to be listed on the import, instead of ``import *`` at least on the documentation. On the environment I am inserted it is considered a violation of "Explicit is better than implicit" and would not pass on a pair review...

...and people will poke other people heads with a stick if this would be tried ;)

**Pull request closed without merging**
